### ISSUE TITLE
/ is an invalid character?

### ISSUE THREAD

**Issue by ghost** [gustavwilliam/shortify#3]
![image](https://user-images.githubusercontent.com/95855603/147807380-f5ddcf59-3e74-492f-a348-78e80e1fa95a.png)

**Comment by gustavwilliam** [comment]
Yes, `/` is an invalid character as of now.

We're quite restrictive with the allowed characters right now, so more options are available further down the line. For example, we're considering adding a `tree` feature; which might use `/`.
